apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-ms-deployment
  name: python-ms-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-ms-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-ms-deployment
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: python-ms-crisp-devops
        resources: {}
status: {}