apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-ms-deployment
  name: python-ms-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 7777
  selector:
    app: python-ms-deployment
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
