# python-manifests/overlays/prod/kustomization.yaml
resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: python-ms-deployment
    path: python-ms-deployment-patch.yml
  
  - target:
      kind: Service
      name: python-ms-svc
    path: python-ms-service-patch.yml