apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang
  namespace: argocd
spec:
  destination:
    namespace: golang-ms
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: ./k8s-manifests-helm/golang-helm
    repoURL: https://github.com/Prajwalmithun/crisp-devops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - Prune=true
    - CreateNamespace=true