apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang-ms-deployment
  name: golang-ms-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8888
  selector:
    app: golang-ms-deployment
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
