apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: golang-ms-deployment
  name: golang-ms-svc
spec:
  ports:
  - port: 888
    protocol: TCP
    targetPort: 8888
  selector:
    app: golang-ms-deployment
  type: NodePort
status:
  loadBalancer: {}
