# Resources : https://github.com/marketplace/actions/build-and-push-docker-images
# https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml
name: ci
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}      # Use secrets for sensitive info
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Use secrets for sensitive info

      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
          push: true
          context: ./microservices/python-microservice  # Set the build context to the directory with the Dockerfile
        #   file: ./microservices/python-microservice/Dockerfile  # Specify the path to the Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/python-ms-crisp-devops:latest    # Use secrets for sensitive info


